change
GovTechSG/TechBiz-Documentation pull request #125
Opened 2023-01-31 04:55 UTC by kpslp

changes!

2023-01-31 09:23 UTC, SenthilKumarSivakami requested changes

2023-01-31 09:23 UTC, SenthilKumarSivakami commented on invite-users.md
> +<kbd>![email_invite](/images/email_invite3.png ':size=100%')</kbd>
image too small, cant see the text on it.

2023-01-31 09:23 UTC, SenthilKumarSivakami commented on invite-users.md
> +2. [Create user account](#create-user-account) - Use this option to invite vendors.
is it Create user account because your screenshot shows only Create account, displayed on the UI?

2023-01-31 09:23 UTC, SenthilKumarSivakami commented on invite-users.md
> +## Create user account
why was it updated to Create "user" account?

2023-02-01 00:23 UTC, kpslp commented on log-in-to-TechBiz-portal.md
> +- Vendors with a Technical admin role in a TechBiz account.
@SenthilKumarSivakami what about "Vendors who are Technical admins in a TechBiz account" ?

2023-02-06 02:36 UTC, closed without merging