stackops
GovTechSG/TechBiz-Documentation pull request #131
Opened 2023-07-27 03:35 UTC by kpslp

2023-08-01 13:22 UTC, denisecollard requested changes
Need to amend with upper case S for "Services"

2023-08-01 13:22 UTC, denisecollard commented on create-subscription-acc/request-for-techbiz-account.md
> +In **Select service(s)**, choose the required **SGTS Service(s)** and click **Next**.
typo : Service(s)

2023-08-01 13:22 UTC, denisecollard commented on create-subscription-acc/request-for-techbiz-account.md
> +4. If you are subscribing to more than one SGTS services, repeat **steps 2-3** and click **Next**.
typo: Services

2023-08-01 13:22 UTC, denisecollard commented on create-techbiz-system.md
> +Agencies need to add and configure TechBiz systems to manage the subscribed SGTS services.
Typo: Services

2023-08-01 13:22 UTC, denisecollard commented on create-techbiz-system.md
> +| **TechBiz system ID** | A unique TechBiz system ID is automatically generated and cannot be edited. The TechBiz system ID is common across all subscribed SGTS services under this account. |
Typo: Services

2023-08-01 13:22 UTC, denisecollard commented on add-and-configure-products.md
> +**To add and configure subscribed services**
Typo: Services

2023-08-01 13:22 UTC, denisecollard commented on create-techbiz-system.md
> +Proceed to [Add and configure services](add-and-configure-products.md)  complete the configuration.
Typo: Services

2023-08-01 13:22 UTC, denisecollard commented on home.md
> +| [Add and configure services](add-and-configure-products.md) </br></br> Add and configure services to your system. | [User management](manage-user-access-subscribed-sgts-products.md) </br></br> Use
Typo: Services

2023-08-01 13:22 UTC, denisecollard commented on manage-announcements.md
> +This section guides how administrators can create announcements and manage them on [TechBiz portal](https://portal.techbiz.suite.gov.sg/). Announcements allow SGTS product owners to broadcast message
Typo: SGTS Service owners

2023-08-01 13:22 UTC, denisecollard commented on manage-user-access-subscribed-sgts-products.md
> +5. Select the required product from the **Services** dropdown list to select the SGTS service tools to manage.
Typo: Service

2023-08-01 13:22 UTC, denisecollard commented on manage-user-access-subscribed-sgts-products.md
> +5. Select the required product from the **Services** dropdown list to select the SGTS product tools to manage.
Typo: SGTS Services tools

2023-08-02 00:27 UTC, denisecollard requested changes
Noticed a couple of "product" term not changed to "Service"

2023-08-02 00:27 UTC, denisecollard commented on create-subscription-acc/request-for-techbiz-account.md
>  | **Product agreement** | Click to view the terms and conditions of the product. |
Typo: Service

2023-08-02 00:27 UTC, denisecollard commented on create-subscription-acc/request-for-techbiz-account.md
>  | **Select a plan** | Select the required subscription plan for a product.</br></br>The displayed subscription plans contain details of the chargeable items in a service and their charges. |
Typo: Service

2023-08-02 02:34 UTC, denisecollard requested changes
To amend "Services" with capital "S" for consistency

2023-08-02 02:34 UTC, denisecollard commented on admin-roles-and-permissions.md
> +- Provide Serviceconfiguration details
Spacing in between: Service configuration

2023-08-02 02:34 UTC, denisecollard commented on create-subscription-acc/request-for-techbiz-account.md
> +In **Select service(s)**, choose the required **SGTS Service(s)** and click **Next**.
Capital S: Service(s)

2023-08-02 02:34 UTC, denisecollard commented on create-subscription-acc/request-for-techbiz-account.md
> +| **Select a plan** | Select the required subscription plan for a service.</br></br>The displayed subscription plans contain details of the chargeable items in a service and their charges. |
Capital S : a Service

2023-08-02 02:34 UTC, denisecollard commented on glossary.md
> +A TechBiz system allows agencies to centrally manage and view their SGTS service subscription plans, billing details, and resource usage within a system. An agency can have multiple systems.
Capital S: SGTS Service

2023-08-02 02:34 UTC, denisecollard commented on manage-user-access-subscribed-sgts-products.md
> +5. Select the required Service from the **Services** dropdown list to select the SGTS service tools to manage.
Capital S: SGTS Service

2023-08-02 03:32 UTC, kpslp commented on manage-user-access-subscribed-sgts-products.md
> +5. Select the required Service from the **Services** dropdown list to select the SGTS service tools to manage.
fixed

2023-08-02 03:32 UTC, kpslp commented on glossary.md
> +A TechBiz system allows agencies to centrally manage and view their SGTS service subscription plans, billing details, and resource usage within a system. An agency can have multiple systems.
fixed

2023-08-02 03:33 UTC, kpslp commented on create-subscription-acc/request-for-techbiz-account.md
> +| **Select a plan** | Select the required subscription plan for a service.</br></br>The displayed subscription plans contain details of the chargeable items in a service and their charges. |
fixed

2023-08-02 03:33 UTC, kpslp commented on create-subscription-acc/request-for-techbiz-account.md
> +In **Select service(s)**, choose the required **SGTS Service(s)** and click **Next**.
fixed

2023-08-02 03:33 UTC, kpslp commented on admin-roles-and-permissions.md
> +- Provide Serviceconfiguration details
fixed

2023-08-02 04:59 UTC, denisecollard approved these changes

2023-08-02 05:01 UTC, merged