Update invite-users.md
GovTechSG/TechBiz-Documentation pull request #57
Opened 2022-10-11 01:18 UTC by kpslp

updates

2022-10-11 03:48 UTC, SenthilKumarSivakami requested changes

2022-10-11 03:48 UTC, SenthilKumarSivakami commented on invite-users.md
> +> - Public officers can also use the TechPass OTP service to create accounts. A TechPass account will automatically be created upon approval.
can we move it to the above paragraph as it is within TB? and the previous paragraph only mentions about TP invite and not SEED. I think we should mention SEED also there.

2022-10-11 03:48 UTC, SenthilKumarSivakami commented on invite-users.md
> +> - Public officers can also use the TechPass OTP service to create accounts. A TechPass account will automatically be created upon approval.
I think we need to update the note for SEED in line 9.

2022-10-11 03:48 UTC, SenthilKumarSivakami commented on invite-users.md
The above note is not clear because some vendors too can follow the same flow as PO. so need to work on the wording part.

2022-10-11 03:48 UTC, SenthilKumarSivakami commented on invite-users.md
> +    - Organisation email address
is a space added here now?

2022-10-11 03:48 UTC, SenthilKumarSivakami commented on invite-users.md
> +> - Public officers can also use the TechPass OTP service to create accounts. A TechPass account will automatically be created upon approval.
in the "log in with TechPass OTP" there is a sample email id specified. Please update it to make it consistent across the docs.

and as discussed earlier, please specify when users can use that login method.

2022-10-11 03:48 UTC, SenthilKumarSivakami commented on invite-users.md
> +> - Organisation email address must be in the format of \<your_name>@\<acronym for your agency>.gov.sg.
why do we need this note here? 
and further, it is not just only this PO email format but also vendors can also be invited via TB, right?

2022-10-11 03:48 UTC, SenthilKumarSivakami commented on invite-users.md
> +2.  In **Overview**, click **Invite users**.
is the alternative method not applicable now?

2022-10-17 09:15 UTC, kpslp commented on invite-users.md
> +> - Public officers can also use the TechPass OTP service to create accounts. A TechPass account will automatically be created upon approval.
@SenthilKumarSivakami for note for SEED, what is required to be updated?

2022-10-17 09:15 UTC, kpslp commented on invite-users.md
> +    - Organisation email address
removed @SenthilKumarSivakami

2022-10-17 09:17 UTC, kpslp commented on invite-users.md
> +> - Organisation email address must be in the format of \<your_name>@\<acronym for your agency>.gov.sg.
yep, agreed on that. will it be ok to remove? @SenthilKumarSivakami

2022-10-17 09:18 UTC, kpslp commented on invite-users.md
> +2.  In **Overview**, click **Invite users**.
it is applicable. but do you think its necessary to point this out? because i thought of just standardising it, therefore removing the alternative method. @SenthilKumarSivakami

2022-10-18 01:33 UTC, merged

2022-10-18 03:18 UTC, SenthilKumarSivakami commented on invite-users.md
> +> - Public officers can also use the TechPass OTP service to create accounts. A TechPass account will automatically be created upon approval.
@kpslp, there are a couple of comments here, kindly let me know which has been fixed.  I don't see any changes except for your query on what is needed to be added for SEED.

2022-10-18 03:21 UTC, SenthilKumarSivakami commented on invite-users.md
> +> - Public officers can also use the TechPass OTP service to create accounts. A TechPass account will automatically be created upon approval.
The current note for SEED just says how to onboard to SEED instead of how to get the onboarding invitation?